
[game_rules]
	#This will make these config options override their game rule values.
	#NOTE: Can be used to help modpack creators enforce certain settings.
	overrideGameRules = false

	[game_rules.game_rules_boolean]
		#Should hyper invasions be able to occur?
		enableHyperInvasions = true
		#Should nightmare invasions be able to occur?
		#NOTE: Hyper invasions must be enabled.
		enableNightmareInvasions = true
		#Will disable explosions, fire, etc... from entities spawned by invasions.
		invasionAntiGrief = false
		#Rather than the invasion occuring once in every 'rarity' days, it will instead be set to occur every 'rarity' days.
		consistentInvasions = false
		#Tiers make certain invasions only able to occur after so many days, turning this off will make the world ignore the day count when selecting invasions.
		tieredInvasions = true
		#Hyper Aggression is what invasion mobs have to target the player from across the world, turning this off will make them use default targeting.
		hyperAggression = true
		#Hyper Charge is what the buffed mobs spawned by invasions have, turning this off will disabled these buffed mobs from spawning (This also disables Hyper invasions).
		hyperCharge = true
		#This determines whether players will be unable to sleep during all invasions.
		forceInvasionSleeplessness = true
		#This determines whether invasion mobs should have an xp boost per kill.
		useXPMultiplier = true
		#Determines if invasion mobs should die when the invasions are over.
		#NOTE: Can be used to reduce server lag.
		mobsDieAtEndOfInvasions = false
		#Determines vexes in invasions have a limited lifespan.
		weakenedInvasionVexes = true
		#Determines if invasion ambience sounds should occur.
		enableInvasionAmbience = true
		#Determines if players be notified when invasions start.
		notifyPlayersAboutInvasions = true
		#Determines if invasions should have zero tick delay.
		zeroTickDelay = false
		#Determines if invasions should occur during the first ender dragon boss fight.
		noInvasionsDuringFirstEnderDragonFight = false

	[game_rules.game_rules_integer]
		#The amount of days until an invasion can start.
		#Range: > 0
		invasionStartDelay = 21
		#The max amount of mobs that can spawn from Primary Invasions at once.
		#NOTE: Reduce for increased performance!
		#Range: > 0
		primaryInvasionMobCap = 100
		#The max amount of mobs that can spawn from Secondary Invasions at once.
		#NOTE: Reduce for increased performance!
		#Range: > 0
		secondaryInvasionMobCap = 25
		#The mob kill limit for the invasion that would cause it to end after the player kills so many mobs from that invasion.
		#NOTE: Setting to 0 will disable the limit, limits specified by a datapack will still apply.
		#Range: > 0
		mobKillLimit = 100
		#Maximum amount of chunks an invasion mob can spawn away from the player.
		#Range: 1 ~ 8
		mobSpawnChunkRadius = 8
		#How many blocks around the player are invasion mobs not allowed to spawn.
		#Range: 1 ~ 256
		noSpawnMobsBlockRadius = 16

[invasions]
	#List of Invasions that can be primary invasions.
	#NOTE: The Invasion's Priority cannot be labeled as Secondary Only!
	#Ex: 'puresuffering:solar_eclipse', 'lostcities:lostcity' (swap '' with quotation marks)
	primaryWhitelist = []
	#List of Dimensions that should use Overworld Invasions.
	#NOTE: May not work with randomly generated dimensions! (RFTools/Mystcraft)
	#Ex: 'twilightforest:twilight_forest', 'lostcities:lostcity' (swap '' with quotation marks)
	overworldLikeDimensions = []
	#List of Dimensions that should use Nether Invasions.
	#NOTE: May not work with randomly generated dimensions! (RFTools/Mystcraft)
	#Ex: 'twilightforest:twilight_forest', 'lostcities:lostcity' (swap '' with quotation marks)
	netherLikeDimensions = []
	#List of Dimensions that should use End Invasions.
	#NOTE: May not work with randomly generated dimensions! (RFTools/Mystcraft)
	#Ex: 'twilightforest:twilight_forest', 'lostcities:lostcity' (swap '' with quotation marks)
	endLikeDimensions = []
	#List of mobs that won't be hyper aggressive towards the player. (If setting is turned on)
	hyperAggressionBlacklist = ["minecraft:vex"]
	#List of mobs that can't be hyper charged. (If setting is turned on)
	hyperChargeBlacklist = ["minecraft:vex"]
	#List of mods that won't be allowed to have their mobs spawn in Biome Boosted Invasions.
	#Ex: 'twilightforest', 'mutantbeasts'
	modBiomeBoostedBlacklist = []
	#List of mobs that won't be allowed to spawn in Biome Boosted Invasions.
	#Ex: 'minecraft:enderman', 'mutantbeasts:mutant_creeper'
	mobBiomeBoostedBlacklist = []
	#The chance of a naturally spawning mob has of spawning during an invasion.
	#NOTE: May affect performance at higher numbers!
	#Range: 0.0 ~ 1.0
	naturalSpawnChance = 0.0025
	#The chance of an invasion mob being hyper charged.
	#Range: 0.0 ~ 1.0
	hyperChargeChance = 0.2
	#How many ticks the Blessing Effect lasts when respawning.
	#Range: > 0
	blessingEffectRespawnDuration = 400
	#How many ticks the Blessing Effect lasts when changing dimensions.
	#Range: > 0
	blessingEffectDimensionChangeDuration = 200
	#List of Invasions that can't occur.
	#Ex: 'puresuffering:solar_eclipse', 'puresuffering:phantom_zone' (swap '' with quotation marks)
	invasionBlacklist = []
	#List of invasion mobs that won't have anti-grief applied to them when the gamerule in active.
	#Ex: 'mutantmonsters:mutant_creeper', 'mutantmonsters:creeper_minion'
	invasionAntiGriefExceptions = []

[text]
	#Start message for default invasions, leave blank to for default message.
	defaultInvasionStartMessage = ""
	#Start message for hyper invasions, leave blank to for default message.
	hyperInvasionStartMessage = ""
	#Start message for nightmare invasions, leave blank to for default message.
	nightmareInvasionStartMessage = ""
	#Cancel message for invasions, leave blank to for default message.
	cancelInvasionStartMessage = ""

