StartupEvents.modifyCreativeTab('kubejs:tab', (event) => {
  event.setIcon('lucky:lucky_world_invasion_lucky_block')
  event.setDisplayName(Text.translate('kubejs.title'))

  event.add('lucky:lucky_world_invasion_lucky_sword')
  event.add('lucky:lucky_block')
  event.add('lucky:elewind_lucky_block')
  event.add('lucky:elergy_lucky_block')
  event.add('lucky:eleice_lucky_block')
  event.add('lucky:elefire_lucky_block')
  event.add('lucky:elemental_lucky_block')
  event.add('lucky:desert_lucky_block')
  event.add('lucky:amongus_lucky_block')
  event.add('lucky:summer_lucky_block')
  event.add('lucky:fire_lucky_block')
  event.add('lucky:water_lucky_block')
  event.add('lucky:morbius_lucky_block')
  event.add('lucky:pink_lucky_block')
  event.add('lucky:lucky_world_invasion_lucky_block')
  event.add('fuze_relics:lucky_blockling_render')
  event.add('integrated_lucky_blocks:lucky_block')
})
