#Amount of damage scale boost per level of Crossfire buff gives
#Range: 2.2250738585072014E-308 ~ 1.7976931348623157E308
crossfire_buff_power = 0.3
#Enable calling hurt function with invokespecial on entities with a specific tag
enable_special_hurt = true
#If true, gun damage will be affect by `minecraft:generic.attack_damage` attribute, then use the result as base value for `gunsmithlib:bullet_damage` attribute
use_attack_damage = true

